name: Daily Commit

on:
  schedule:
    - cron: "20 16 * * *" # Runs daily at 10:20 UTC (15:50 IST)
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write  # This allows the workflow to push commits

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git (nitin.nitnav@gramener.com)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "nitin.nitnav@gramener.com"

      - name: Make a Commit
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt
          git commit -m "Daily commit: $(date)"
          git push
